### ISSUE TITLE
大佬，在19.07官方源码中用官源的luci 18.06杂交，编译不成功。在固件中安装你编译好的ipk，X86固件下，无法改MAC

### ISSUE THREAD

**Issue by lllrrr2** [muink/luci-app-change-mac#1]
大佬，在19.07官方源码中用官源的luci 18.06杂交，编译不成功。在固件中安装你编译好的ipk，X86固件下，无法改MAC，请大佬指点

**Comment by muink** [comment]
没有安装依赖[openwrt-rgmac](https://github.com/muink/openwrt-rgmac)
编译也需要先编译openwrt-rgmac，再编译luci

**Comment by lllrrr** [comment]
是要先编译好openwrt-rgmac吗，我有git clone openwrt-rgmac包下来，编译的时候也有选中，一起编译不行。

**Comment by lllrrr** [comment]
我再试试，先单独编译openwrt-rgmac

**Comment by muink** [comment]
> 我再试试，先单独编译openwrt-rgmac

rgmac 本身是bash脚本, 各平台都没差别, 可以直接用 `release` 分支里的预编译包
